### ISSUE TITLE
No module named tica_metadynamics.pyplumed

### ISSUE THREAD

**Issue by roadhouse23** [msultan/tica_metadynamics#6]
Hello,
I succesfully installed tica_metadynamics after installing plumed and all the dependencies indicated in requirements.txt.
However, when I try to execute the test_project_setup.py I got the following:

"ModuleNotFoundError: No module named 'tica_metadynamics.pyplumed"

Thank you for your time.

Gianvito

**Comment by msultan** [comment]
ahh thats definitely a bug where i havent added that module to the main python package. A quick fix is to do install a developmental copy

``` python setup.py develop ``` 

instead of a plain install

```python setup.py install```

**Comment by msultan** [comment]
I appreciate the report, I will try and fix this asap.

**Comment by roadhouse23** [comment]
Ok thanks, I installed with develop option and now it seems to be ok.

Is there something to obtain as result of a succesfull test?





Il giorno mer 8 ago 2018 alle ore 20:07 msultan <notifications@github.com>
ha scritto:

**Comment by msultan** [comment]
I would try running through the SML_CV example notebooks, if it can generate the same outputs thats a good sign.
